= Asciidoctor extensions
:icon: font

A set of AsciidoctorJ extensions

image:https://buildhive.cloudbees.com/job/binout/job/asciidoctor-extensions/badge/icon["Build Status", link="https://buildhive.cloudbees.com/job/binout/job/asciidoctor-extensions/"]

== How it works ?

Refer to AsciidoctorJ documentation : http://asciidoctor.org/docs/asciidoctorj/#extension-api

== Extensions

NOTE: the prefix package of class name of extensions is `com.github.binout` and not `io.github.binout` (as groupId)
because of a bug in JRuby loading

=== Twitter Macro

Type:: org.asciidoctor.extension.InlineMacroProcessor
Class:: com.github.binout.asciidoctor.extensions.TwitterMacro
Example:: twiiter::binout[]

=== Uri Include Processor

Type:: org.asciidoctor.extension.IncludeProcessor
Class:: com.github.binout.asciidoctor.extensions.UriIncludeProcessor
Example:: include::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/Gemfile[]

=== Gist Macro

Type:: org.asciidoctor.extension.BlockMacroProcessor
Class:: com.github.binout.asciidoctor.extensions.GistMacro
Example:: gist::5732518[]